const CATEGORIES = {
  math: { label:'Math Reflex', icon:'🔢', color:'#00E5FF', type:'mcq', questions:[
    {tag:'MATH',prompt:'What is 7 × 8?',word:'7 × 8',options:['54','56','58','64'],answer:'56'},
    {tag:'MATH',prompt:'What is 9 × 7?',word:'9 × 7',options:['54','63','72','81'],answer:'63'},
    {tag:'MATH',prompt:'What is 12 × 12?',word:'12²',options:['124','144','132','148'],answer:'144'},
    {tag:'MATH',prompt:'What is 15 × 4?',word:'15 × 4',options:['50','55','60','65'],answer:'60'},
    {tag:'MATH',prompt:'What is 8 × 8?',word:'8 × 8',options:['56','62','64','66'],answer:'64'},
    {tag:'MATH',prompt:'What is 6 × 7?',word:'6 × 7',options:['36','40','42','48'],answer:'42'},
    {tag:'MATH',prompt:'What is 11 × 11?',word:'11²',options:['111','121','131','141'],answer:'121'},
    {tag:'MATH',prompt:'What is 9 × 9?',word:'9 × 9',options:['72','81','90','99'],answer:'81'},
    {tag:'MATH',prompt:'Square root of 144?',word:'√144',options:['11','12','13','14'],answer:'12'},
    {tag:'MATH',prompt:'What is 25% of 200?',word:'25% × 200',options:['40','50','60','75'],answer:'50'},
    {tag:'MATH',prompt:'What is 2^10?',word:'2¹⁰',options:['512','1024','2048','256'],answer:'1024'},
    {tag:'MATH',prompt:'What is 3^4?',word:'3⁴',options:['27','54','81','108'],answer:'81'},
    {tag:'MATH',prompt:'What is 18 × 4?',word:'18 × 4',options:['62','68','72','76'],answer:'72'},
    {tag:'MATH',prompt:'What is 8 × 9?',word:'8 × 9',options:['63','72','81','90'],answer:'72'},
    {tag:'MATH',prompt:'How many degrees in a triangle?',word:'△°',options:['90','120','180','360'],answer:'180'},
    {tag:'MATH',prompt:'How many degrees in a circle?',word:'○°',options:['90','180','270','360'],answer:'360'},
    {tag:'MATH',prompt:'What is 2^8?',word:'2⁸',options:['128','256','512','1024'],answer:'256'},
    {tag:'MATH',prompt:'Area of rectangle 8×6?',word:'A=8×6',options:['28','36','40','48'],answer:'48'},
    {tag:'MATH',prompt:'What is 10³?',word:'10³',options:['100','1000','10000','100000'],answer:'1000'},
    {tag:'MATH',prompt:'Hypotenuse of 3-4-? triangle?',word:'3²+4²=?²',options:['4','5','6','7'],answer:'5'},
    {tag:'MATH',prompt:'What is 50% of 90?',word:'50% × 90',options:['40','45','50','55'],answer:'45'},
    {tag:'MATH',prompt:'What is 100 ÷ 4?',word:'100 ÷ 4',options:['20','25','30','40'],answer:'25'},
    {tag:'MATH',prompt:'What is 7²?',word:'7²',options:['42','49','56','63'],answer:'49'},
    {tag:'MATH',prompt:'What is 6³?',word:'6³',options:['186','196','216','226'],answer:'216'},
    {tag:'MATH',prompt:'What is 5!?',word:'5!',options:['60','100','120','150'],answer:'120'},
    {tag:'MATH',prompt:'What is 16 × 16?',word:'16²',options:['246','256','266','276'],answer:'256'},
    {tag:'MATH',prompt:'What is 13²?',word:'13²',options:['159','169','179','189'],answer:'169'},
    {tag:'MATH',prompt:'What is 25²?',word:'25²',options:['525','575','625','675'],answer:'625'},
    {tag:'MATH',prompt:'LCM of 4 and 6?',word:'LCM(4,6)',options:['8','10','12','14'],answer:'12'},
    {tag:'MATH',prompt:'GCF of 12 and 18?',word:'GCF(12,18)',options:['3','4','6','9'],answer:'6'},
    {tag:'MATH',prompt:'What is 40% of 250?',word:'40% × 250',options:['80','90','100','110'],answer:'100'},
    {tag:'MATH',prompt:'How many sides in a hexagon?',word:'Hexagon',options:['5','6','7','8'],answer:'6'},
    {tag:'MATH',prompt:'What is 72 ÷ 8?',word:'72 ÷ 8',options:['7','8','9','10'],answer:'9'},
    {tag:'MATH',prompt:'What is 1+2+3+...+10?',word:'Σ1→10',options:['45','50','55','60'],answer:'55'},
    {tag:'MATH',prompt:'How many cm in a meter?',word:'1m=?cm',options:['10','100','1000','10000'],answer:'100'},
    {tag:'MATH',prompt:'What is 3/4 of 200?',word:'¾×200',options:['100','125','150','175'],answer:'150'},
    {tag:'MATH',prompt:'What is 1000 ÷ 25?',word:'1000÷25',options:['30','35','40','45'],answer:'40'},
    {tag:'MATH',prompt:'What is pi to 2 decimal places?',word:'π≈?',options:['3.12','3.14','3.16','3.18'],answer:'3.14'},
    {tag:'MATH',prompt:'What is 30% of 90?',word:'30%×90',options:['24','27','30','33'],answer:'27'},
    {tag:'MATH',prompt:'What is 88 ÷ 8?',word:'88÷8',options:['9','10','11','12'],answer:'11'},
    {tag:'MATH',prompt:'What is 7 × 11?',word:'7×11',options:['67','74','77','84'],answer:'77'},
    {tag:'MATH',prompt:'What is 4 × 25?',word:'4×25',options:['80','90','100','110'],answer:'100'},
    {tag:'MATH',prompt:'What is 120 ÷ 8?',word:'120÷8',options:['12','14','15','16'],answer:'15'},
    {tag:'MATH',prompt:'What is 50 × 50?',word:'50²',options:['2000','2250','2500','2750'],answer:'2500'},
    {tag:'MATH',prompt:'What is 1/3 of 90?',word:'90÷3',options:['20','25','30','35'],answer:'30'},
    {tag:'MATH',prompt:'What is 60% of 500?',word:'60%×500',options:['250','280','300','320'],answer:'300'},
    {tag:'MATH',prompt:'What is x in 2x=16?',word:'2x=16',options:['6','7','8','9'],answer:'8'},
    {tag:'MATH',prompt:'What is x in x+13=20?',word:'x+13=20',options:['5','6','7','8'],answer:'7'},
    {tag:'MATH',prompt:'What is 5×12?',word:'5×12',options:['50','55','60','65'],answer:'60'},
    {tag:'MATH',prompt:'What is 9×11?',word:'9×11',options:['88','99','100','109'],answer:'99'},
    {tag:'MATH',prompt:'What is 15% of 300?',word:'15%×300',options:['30','40','45','50'],answer:'45'},
    {tag:'MATH',prompt:'What is 17²?',word:'17²',options:['269','279','289','299'],answer:'289'},
    {tag:'MATH',prompt:'Perimeter of square with side 7?',word:'P=4×7',options:['21','24','28','32'],answer:'28'},
    {tag:'MATH',prompt:'What is 20% of 150?',word:'20%×150',options:['20','25','30','35'],answer:'30'},
    {tag:'MATH',prompt:'What is 14²?',word:'14²',options:['186','192','196','202'],answer:'196'},
    {tag:'MATH',prompt:'What is 10% of 850?',word:'10%×850',options:['75','80','85','90'],answer:'85'},
    {tag:'MATH',prompt:'What is 250 × 4?',word:'250×4',options:['800','900','1000','1100'],answer:'1000'},
    {tag:'MATH',prompt:'What is the next prime after 7?',word:'Prime>7',options:['8','9','10','11'],answer:'11'},
    {tag:'MATH',prompt:'What is 180 ÷ 12?',word:'180÷12',options:['12','14','15','16'],answer:'15'},
    {tag:'MATH',prompt:'What is 2⁵?',word:'2×2×2×2×2',options:['16','32','64','128'],answer:'32'},
    {tag:'MATH',prompt:'What is 1/8 as a decimal?',word:'1/8=?',options:['0.1','0.125','0.15','0.175'],answer:'0.125'},
    {tag:'MATH',prompt:'Sum of angles in a quadrilateral?',word:'□ angles',options:['180°','270°','360°','450°'],answer:'360°'},
    {tag:'MATH',prompt:'What is 111 × 9?',word:'111×9',options:['889','989','999','1089'],answer:'999'},
    {tag:'MATH',prompt:'What is 99²?',word:'99²',options:['9601','9801','9901','10001'],answer:'9801'},
    {tag:'MATH',prompt:'How many sides in an octagon?',word:'Octagon',options:['6','7','8','9'],answer:'8'},
    {tag:'MATH',prompt:'What is 4⁴?',word:'4⁴',options:['128','256','512','1024'],answer:'256'},
    {tag:'MATH',prompt:'What is 75% of 80?',word:'75%×80',options:['55','60','65','70'],answer:'60'},
    {tag:'MATH',prompt:'What is 12 × 9?',word:'12×9',options:['96','100','108','116'],answer:'108'},
    {tag:'MATH',prompt:'What is 33 × 3?',word:'33×3',options:['89','96','99','102'],answer:'99'},
    {tag:'MATH',prompt:'What is 19 × 5?',word:'19×5',options:['85','90','95','100'],answer:'95'},
    {tag:'MATH',prompt:'What is 45 × 2?',word:'45×2',options:['80','85','90','95'],answer:'90'},
    {tag:'MATH',prompt:'What is 256 ÷ 8?',word:'256÷8',options:['28','30','32','34'],answer:'32'},
    {tag:'MATH',prompt:'What is 11 × 13?',word:'11×13',options:['133','143','153','163'],answer:'143'},
    {tag:'MATH',prompt:'What is 1001 ÷ 7?',word:'1001÷7',options:['133','143','153','163'],answer:'143'},
    {tag:'MATH',prompt:'What is 13 × 5?',word:'13×5',options:['55','60','65','70'],answer:'65'},
    {tag:'MATH',prompt:'What is √225?',word:'√225',options:['13','14','15','16'],answer:'15'},
    {tag:'MATH',prompt:'What is 24 ÷ 0.5?',word:'24÷0.5',options:['12','36','48','60'],answer:'48'},
    {tag:'MATH',prompt:'What is 0.1 × 0.1?',word:'0.1²',options:['0.001','0.01','0.1','1'],answer:'0.01'},
    {tag:'MATH',prompt:'What is 1 million in numerals?',word:'1 million',options:['10,000','100,000','1,000,000','10,000,000'],answer:'1,000,000'},
    {tag:'MATH',prompt:'What is 3/5 as a percentage?',word:'3/5=?%',options:['50%','55%','60%','65%'],answer:'60%'},
    {tag:'MATH',prompt:'What is the Fibonacci number after 13?',word:'Fib after 13',options:['18','19','20','21'],answer:'21'},
    {tag:'MATH',prompt:'What is 10 × 10 × 10?',word:'10³',options:['100','1000','10000','100000'],answer:'1000'},
    {tag:'MATH',prompt:'What is 8! ÷ 7!?',word:'8!/7!',options:['6','7','8','9'],answer:'8'},
    {tag:'MATH',prompt:'What is 14 × 3?',word:'14×3',options:['38','40','42','44'],answer:'42'},
    {tag:'MATH',prompt:'What is 7³?',word:'7³',options:['293','313','333','343'],answer:'343'},
    {tag:'MATH',prompt:'What is 200 × 0.5?',word:'200×0.5',options:['50','75','100','125'],answer:'100'},
    {tag:'MATH',prompt:'What is 450 ÷ 9?',word:'450÷9',options:['45','50','55','60'],answer:'50'},
    {tag:'MATH',prompt:'What is 1000 - 375?',word:'1000-375',options:['525','615','625','635'],answer:'625'},
    {tag:'MATH',prompt:'What is 999 + 1?',word:'999+1',options:['999','1000','1001','1010'],answer:'1000'},
    {tag:'MATH',prompt:'Prime number between 10 and 15?',word:'Prime 10-15',options:['11','12','14','15'],answer:'11'},
    {tag:'MATH',prompt:'What is 5 × 5 × 4?',word:'5×5×4',options:['80','90','100','120'],answer:'100'},
  ]},

  rialo: { label:'Rialo & Web3', icon:'🎮', color:'#8A2BE2', type:'mcq', questions:[
    {tag:'RIALO',prompt:'What is Rialo?',word:'Rialo',options:['A DeFi protocol','A competitive gaming platform','An NFT marketplace','A blockchain'],answer:'A competitive gaming platform'},
    {tag:'RIALO',prompt:'Rialo rewards players with?',word:'Rewards',options:['NFTs only','Tokens','Fiat cash','Points only'],answer:'Tokens'},
    {tag:'RIALO',prompt:'What is Rialo game genre?',word:'Genre',options:['RPG','DeFi','Competitive Gaming','Strategy'],answer:'Competitive Gaming'},
    {tag:'WEB3',prompt:'What does NFT stand for?',word:'NFT',options:['Non-Fungible Token','New Finance Tech','Net Fund Token','Network File Transfer'],answer:'Non-Fungible Token'},
    {tag:'WEB3',prompt:'What does DeFi stand for?',word:'DeFi',options:['Decentralized Finance','Digital Finance','Distributed Fiat','Deferred Financing'],answer:'Decentralized Finance'},
    {tag:'WEB3',prompt:'Ethereum consensus mechanism?',word:'Ethereum',options:['Proof of Work','Proof of Stake','Delegated PoS','PoA'],answer:'Proof of Stake'},
    {tag:'WEB3',prompt:'What is a smart contract?',word:'Smart contract',options:['A legal document','Self-executing blockchain code','A type of wallet','An NFT standard'],answer:'Self-executing blockchain code'},
    {tag:'WEB3',prompt:'What does WAGMI mean?',word:'WAGMI',options:['We Are Getting More Inu','We All Gonna Make It','Web3 Arena Game Mode Incoming','Wait And Get More Info'],answer:'We All Gonna Make It'},
    {tag:'WEB3',prompt:'What is a gas fee?',word:'Gas fee',options:['Network transaction cost','Mining reward','Staking yield','Burn fee'],answer:'Network transaction cost'},
    {tag:'WEB3',prompt:'What is staking?',word:'Staking',options:['Selling tokens','Locking tokens to earn rewards','Mining blocks','Burning tokens'],answer:'Locking tokens to earn rewards'},
    {tag:'WEB3',prompt:'What is a blockchain?',word:'Blockchain',options:['A type of cloud','Distributed immutable ledger','A programming language','A social network'],answer:'Distributed immutable ledger'},
    {tag:'WEB3',prompt:'What is minting an NFT?',word:'Minting',options:['Selling an NFT','Creating an NFT on-chain','Staking an NFT','Burning an NFT'],answer:'Creating an NFT on-chain'},
    {tag:'WEB3',prompt:'What is a DAO?',word:'DAO',options:['Digital Asset Organization','Decentralized Autonomous Organization','Data Access Object','Distributed App Operation'],answer:'Decentralized Autonomous Organization'},
    {tag:'WEB3',prompt:'What is a seed phrase?',word:'Seed phrase',options:['A mining password','12-24 words to recover a wallet','A smart contract function','A transaction hash'],answer:'12-24 words to recover a wallet'},
    {tag:'WEB3',prompt:'What does APY stand for?',word:'APY',options:['Annual Percentage Yield','Asset Pool Year','Automated Protocol Yield','Annual Protocol Yield'],answer:'Annual Percentage Yield'},
    {tag:'WEB3',prompt:'What is a DEX?',word:'DEX',options:['Digital Exchange','Decentralized Exchange','Derivative Exchange','Data Exchange'],answer:'Decentralized Exchange'},
    {tag:'WEB3',prompt:'What does HODL mean?',word:'HODL',options:['Hold On for Dear Life','High Order Digital Ledger','Hold or Drop Later','High Output Digital Layer'],answer:'Hold On for Dear Life'},
    {tag:'WEB3',prompt:'What is a rug pull?',word:'Rug pull',options:['A crypto upgrade','Developers abandoning project with funds','A staking mechanism','A governance vote'],answer:'Developers abandoning project with funds'},
    {tag:'WEB3',prompt:'What is FUD in crypto?',word:'FUD',options:['Fear Uncertainty Doubt','Fast Utility Demand','Full User Data','Fund Utility Distribution'],answer:'Fear Uncertainty Doubt'},
    {tag:'WEB3',prompt:'What is TVL in DeFi?',word:'TVL',options:['Total Value Locked','Token Volume Ledger','Trade Verification Layer','Total Vault Liquidity'],answer:'Total Value Locked'},
    {tag:'WEB3',prompt:'What does P2E mean?',word:'P2E',options:['Play to Earn','Pay to Enter','Proof to Execute','Protocol to Ecosystem'],answer:'Play to Earn'},
    {tag:'WEB3',prompt:'What is a crypto airdrop?',word:'Airdrop',options:['A token sale','Free token distribution','A NFT mint','A governance vote'],answer:'Free token distribution'},
    {tag:'WEB3',prompt:'What is yield farming?',word:'Yield farming',options:['Mining crypto','Earning rewards by providing liquidity','Staking only','Trading bots'],answer:'Earning rewards by providing liquidity'},
    {tag:'WEB3',prompt:'What is a floor price (NFTs)?',word:'Floor price',options:['Highest price','Lowest listed price','Average price','Burned token price'],answer:'Lowest listed price'},
    {tag:'WEB3',prompt:'What does GM mean in Web3?',word:'GM',options:['Good Market','Good Morning','Game Mode','General Mint'],answer:'Good Morning'},
    {tag:'WEB3',prompt:'What is tokenomics?',word:'Tokenomics',options:['Token trading strategy','Economics of token supply/distribution','Mining rewards','Gas fee structure'],answer:'Economics of token supply/distribution'},
    {tag:'WEB3',prompt:'What is an ERC-20 token?',word:'ERC-20',options:['An NFT standard','A fungible token standard on Ethereum','A wallet type','A bridge protocol'],answer:'A fungible token standard on Ethereum'},
    {tag:'WEB3',prompt:'What is ERC-721?',word:'ERC-721',options:['Fungible token standard','NFT standard on Ethereum','A DeFi protocol','A consensus mechanism'],answer:'NFT standard on Ethereum'},
    {tag:'WEB3',prompt:'What is slippage in crypto?',word:'Slippage',options:['A network outage','Price change between expected and executed trade','A gas spike','A token burn'],answer:'Price change between expected and executed trade'},
    {tag:'WEB3',prompt:'What is burning tokens?',word:'Token burn',options:['Trading tokens','Sending tokens to unspendable address','Staking tokens','Wrapping tokens'],answer:'Sending tokens to unspendable address'},
    {tag:'WEB3',prompt:'What is a Layer 2?',word:'Layer 2',options:['A sidechain','Scaling solution on top of Layer 1','A new blockchain','A consensus mechanism'],answer:'Scaling solution on top of Layer 1'},
    {tag:'WEB3',prompt:'What is a mempool?',word:'Mempool',options:['A mining pool','Pool of unconfirmed transactions','A liquidity pool','A staking pool'],answer:'Pool of unconfirmed transactions'},
    {tag:'WEB3',prompt:'What is market cap in crypto?',word:'Market cap',options:['Total trading volume','Price × circulating supply','Total supply value','24h trade value'],answer:'Price × circulating supply'},
    {tag:'WEB3',prompt:'What is NGMI?',word:'NGMI',options:['Not Gonna Make It','New Game Mode Initiative','Next Gen Market Index','Node Graph Mining Interface'],answer:'Not Gonna Make It'},
    {tag:'WEB3',prompt:'What is a genesis block?',word:'Genesis block',options:['Last block','First block in a blockchain','A reward block','A checkpoint block'],answer:'First block in a blockchain'},
    {tag:'WEB3',prompt:'What is a cold wallet?',word:'Cold wallet',options:['An online wallet','Offline hardware wallet','A mobile wallet','A paper wallet'],answer:'Offline hardware wallet'},
    {tag:'WEB3',prompt:'What is block time?',word:'Block time',options:['Time to mine all coins','Time between blocks','Confirmation time','Network latency'],answer:'Time between blocks'},
    {tag:'WEB3',prompt:'What is a governance token?',word:'Governance token',options:['A stablecoin','Token that grants voting rights','An NFT','A wrapped token'],answer:'Token that grants voting rights'},
    {tag:'WEB3',prompt:'What is a hash in blockchain?',word:'Hash',options:['A transaction fee','Fixed-length output from data','A wallet address','A smart contract'],answer:'Fixed-length output from data'},
    {tag:'WEB3',prompt:'What is a node in blockchain?',word:'Node',options:['A token','Computer in the network','A smart contract','A wallet address'],answer:'Computer in the network'},
    {tag:'WEB3',prompt:'What is a liquidity pool?',word:'Liquidity pool',options:['A staking pool','Assets locked in a smart contract for trading','A mining pool','A governance pool'],answer:'Assets locked in a smart contract for trading'},
    {tag:'WEB3',prompt:'What is FOMO in crypto?',word:'FOMO',options:['Fear Of Missing Out','Full On Market Operation','Fast Order Market Option','Fixed Output Mining Operation'],answer:'Fear Of Missing Out'},
    {tag:'WEB3',prompt:'What is a whitepaper?',word:'Whitepaper',options:['A trading guide','Technical document describing a project','An NFT listing','A governance proposal'],answer:'Technical document describing a project'},
    {tag:'WEB3',prompt:'What is impermanent loss?',word:'Impermanent loss',options:['A network fee','Loss from providing liquidity vs holding','A gas error','A failed transaction'],answer:'Loss from providing liquidity vs holding'},
    {tag:'WEB3',prompt:'What is a crypto wallet?',word:'Wallet',options:['A bank account','Software to store crypto keys','An exchange','A token'],answer:'Software to store crypto keys'},
    {tag:'WEB3',prompt:'What is a token bridge?',word:'Bridge',options:['A DEX','Transfer tokens between blockchains','A staking pool','An NFT standard'],answer:'Transfer tokens between blockchains'},
    {tag:'WEB3',prompt:'What is a validator in PoS?',word:'Validator',options:['A miner','Node validating transactions by staking','A bridge operator','A DEX liquidity provider'],answer:'Node validating transactions by staking'},
    {tag:'WEB3',prompt:'What is a testnet?',word:'Testnet',options:['A trading bot','Blockchain test environment','A mining pool','A staking pool'],answer:'Blockchain test environment'},
    {tag:'WEB3',prompt:'What is wrapped Ether (WETH)?',word:'WETH',options:['A stablecoin','ERC-20 version of ETH','A Layer 2 token','A governance token'],answer:'ERC-20 version of ETH'},
    {tag:'WEB3',prompt:'What is a paper wallet?',word:'Paper wallet',options:['A printed private key','A web wallet','A hardware device','A mobile app'],answer:'A printed private key'},
  ]},

  science: { label:'Science', icon:'🔬', color:'#00FF9C', type:'mcq', questions:[
    {tag:'SCIENCE',prompt:'Chemical symbol for water?',word:'Water',options:['HO','H2O','H3O','OH2'],answer:'H2O'},
    {tag:'SCIENCE',prompt:'Planet closest to the Sun?',word:'Closest planet',options:['Venus','Earth','Mercury','Mars'],answer:'Mercury'},
    {tag:'SCIENCE',prompt:'Speed of light?',word:'Speed of light',options:['300,000 km/s','150,000 km/s','500,000 km/s','1,000,000 km/s'],answer:'300,000 km/s'},
    {tag:'SCIENCE',prompt:'How many bones in the human body?',word:'Human bones',options:['186','196','206','216'],answer:'206'},
    {tag:'SCIENCE',prompt:'Powerhouse of the cell?',word:'Cell power',options:['Nucleus','Ribosome','Mitochondria','Vacuole'],answer:'Mitochondria'},
    {tag:'SCIENCE',prompt:'What gas do plants absorb?',word:'Plants absorb',options:['Oxygen','Nitrogen','CO2','Hydrogen'],answer:'CO2'},
    {tag:'SCIENCE',prompt:'Atomic number of carbon?',word:'Carbon',options:['4','6','8','12'],answer:'6'},
    {tag:'SCIENCE',prompt:'Largest planet?',word:'Largest planet',options:['Saturn','Neptune','Jupiter','Uranus'],answer:'Jupiter'},
    {tag:'SCIENCE',prompt:'Boiling point of water?',word:'Water boils',options:['90°C','95°C','100°C','105°C'],answer:'100°C'},
    {tag:'SCIENCE',prompt:'Most abundant gas in air?',word:'Air is mostly',options:['Oxygen','CO2','Nitrogen','Argon'],answer:'Nitrogen'},
    {tag:'SCIENCE',prompt:'How many chromosomes in human cells?',word:'Chromosomes',options:['23','46','48','52'],answer:'46'},
    {tag:'SCIENCE',prompt:'Chemical formula for salt?',word:'Salt',options:['NaCl','KCl','CaCl','MgCl'],answer:'NaCl'},
    {tag:'SCIENCE',prompt:'Hardest natural substance?',word:'Hardest',options:['Gold','Iron','Diamond','Quartz'],answer:'Diamond'},
    {tag:'SCIENCE',prompt:'What is DNA made of?',word:'DNA',options:['Amino acids','Nucleotides','Fatty acids','Sugars'],answer:'Nucleotides'},
    {tag:'SCIENCE',prompt:'Symbol for gold?',word:'Gold symbol',options:['Go','Gd','Au','Ag'],answer:'Au'},
    {tag:'SCIENCE',prompt:'Symbol for iron?',word:'Iron symbol',options:['Ir','In','Fe','Fn'],answer:'Fe'},
    {tag:'SCIENCE',prompt:'Unit of electrical resistance?',word:'Resistance unit',options:['Volt','Ampere','Watt','Ohm'],answer:'Ohm'},
    {tag:'SCIENCE',prompt:'Unit of frequency?',word:'Frequency unit',options:['Hertz','Joule','Tesla','Pascal'],answer:'Hertz'},
    {tag:'SCIENCE',prompt:'pH of pure water?',word:'Water pH',options:['5','6','7','8'],answer:'7'},
    {tag:'SCIENCE',prompt:'What is photosynthesis?',word:'Photosynthesis',options:['Breathing','Converting light to energy','Digestion','Cell division'],answer:'Converting light to energy'},
    {tag:'SCIENCE',prompt:'How many hearts does an octopus have?',word:'Octopus hearts',options:['1','2','3','4'],answer:'3'},
    {tag:'SCIENCE',prompt:'Freezing point of water?',word:'Water freezes',options:['-10°C','0°C','5°C','10°C'],answer:'0°C'},
    {tag:'SCIENCE',prompt:'Center of an atom?',word:'Atom center',options:['Core','Nucleus','Shell','Orbit'],answer:'Nucleus'},
    {tag:'SCIENCE',prompt:'Most common element in universe?',word:'Most common',options:['Helium','Carbon','Oxygen','Hydrogen'],answer:'Hydrogen'},
    {tag:'SCIENCE',prompt:'What type of wave is light?',word:'Light wave',options:['Sound wave','Mechanical wave','Electromagnetic wave','Seismic wave'],answer:'Electromagnetic wave'},
    {tag:'SCIENCE',prompt:'How many teeth does an adult have?',word:'Adult teeth',options:['28','30','32','34'],answer:'32'},
    {tag:'SCIENCE',prompt:'Symbol for oxygen?',word:'Oxygen',options:['O','Ox','Om','Og'],answer:'O'},
    {tag:'SCIENCE',prompt:'Largest organ in human body?',word:'Largest organ',options:['Liver','Lungs','Brain','Skin'],answer:'Skin'},
    {tag:'SCIENCE',prompt:'What is a light-year?',word:'Light-year',options:['A time unit','Distance light travels in 1 year','Speed of light','Energy unit'],answer:'Distance light travels in 1 year'},
    {tag:'SCIENCE',prompt:'Symbol for sodium?',word:'Sodium',options:['So','Sd','Na','Nm'],answer:'Na'},
    {tag:'SCIENCE',prompt:'What force keeps planets in orbit?',word:'Orbit force',options:['Magnetism','Nuclear force','Gravity','Electromagnetism'],answer:'Gravity'},
    {tag:'SCIENCE',prompt:'Planet with most moons?',word:'Most moons',options:['Jupiter','Saturn','Uranus','Neptune'],answer:'Saturn'},
    {tag:'SCIENCE',prompt:'Study of fungi?',word:'Fungi study',options:['Botany','Zoology','Mycology','Entomology'],answer:'Mycology'},
    {tag:'SCIENCE',prompt:'What organ pumps blood?',word:'Blood pump',options:['Lungs','Liver','Kidneys','Heart'],answer:'Heart'},
    {tag:'SCIENCE',prompt:'Smallest planet?',word:'Smallest planet',options:['Mars','Venus','Earth','Mercury'],answer:'Mercury'},
  ]},

  geography: { label:'Geography', icon:'🌍', color:'#FFB800', type:'mcq', questions:[
    {tag:'GEO',prompt:'Capital of France?',word:'France 🇫🇷',options:['Lyon','Marseille','Paris','Bordeaux'],answer:'Paris'},
    {tag:'GEO',prompt:'Capital of Japan?',word:'Japan 🇯🇵',options:['Osaka','Kyoto','Hiroshima','Tokyo'],answer:'Tokyo'},
    {tag:'GEO',prompt:'Largest country by area?',word:'Largest country',options:['USA','Canada','China','Russia'],answer:'Russia'},
    {tag:'GEO',prompt:'Most populous country?',word:'Most people',options:['USA','India','China','Indonesia'],answer:'India'},
    {tag:'GEO',prompt:'Longest river in the world?',word:'Longest river',options:['Amazon','Mississippi','Congo','Nile'],answer:'Nile'},
    {tag:'GEO',prompt:'Tallest mountain?',word:'Tallest peak',options:['K2','Kangchenjunga','Everest','Lhotse'],answer:'Everest'},
    {tag:'GEO',prompt:'Capital of Nigeria?',word:'Nigeria 🇳🇬',options:['Lagos','Kano','Ibadan','Abuja'],answer:'Abuja'},
    {tag:'GEO',prompt:'What continent is Brazil on?',word:'Brazil',options:['Africa','Asia','North America','South America'],answer:'South America'},
    {tag:'GEO',prompt:'Largest ocean?',word:'Largest ocean',options:['Atlantic','Indian','Arctic','Pacific'],answer:'Pacific'},
    {tag:'GEO',prompt:'Capital of Australia?',word:'Australia 🇦🇺',options:['Sydney','Melbourne','Brisbane','Canberra'],answer:'Canberra'},
    {tag:'GEO',prompt:'Capital of Germany?',word:'Germany 🇩🇪',options:['Munich','Hamburg','Frankfurt','Berlin'],answer:'Berlin'},
    {tag:'GEO',prompt:'Capital of Egypt?',word:'Egypt 🇪🇬',options:['Alexandria','Luxor','Aswan','Cairo'],answer:'Cairo'},
    {tag:'GEO',prompt:'Smallest country?',word:'Smallest country',options:['Monaco','San Marino','Liechtenstein','Vatican City'],answer:'Vatican City'},
    {tag:'GEO',prompt:'What is the Sahara?',word:'Sahara',options:['Largest jungle','Largest hot desert','Largest cold desert','Largest swamp'],answer:'Largest hot desert'},
    {tag:'GEO',prompt:'Capital of Brazil?',word:'Brazil 🇧🇷',options:['São Paulo','Rio de Janeiro','Brasília','Salvador'],answer:'Brasília'},
    {tag:'GEO',prompt:'Capital of India?',word:'India 🇮🇳',options:['Mumbai','Kolkata','Chennai','New Delhi'],answer:'New Delhi'},
    {tag:'GEO',prompt:'Capital of South Africa?',word:'South Africa 🇿🇦',options:['Cape Town','Johannesburg','Durban','Pretoria'],answer:'Pretoria'},
    {tag:'GEO',prompt:'What language is spoken in Brazil?',word:'Brazil speaks',options:['Spanish','French','Portuguese','English'],answer:'Portuguese'},
    {tag:'GEO',prompt:'How many continents?',word:'Continents',options:['5','6','7','8'],answer:'7'},
    {tag:'GEO',prompt:'Capital of Canada?',word:'Canada 🇨🇦',options:['Toronto','Vancouver','Montreal','Ottawa'],answer:'Ottawa'},
    {tag:'GEO',prompt:'Largest desert in the world?',word:'Largest desert',options:['Sahara','Gobi','Atacama','Antarctic'],answer:'Antarctic'},
    {tag:'GEO',prompt:'Mount Fuji is in which country?',word:'Mt Fuji',options:['China','South Korea','Japan','Taiwan'],answer:'Japan'},
    {tag:'GEO',prompt:'Capital of Spain?',word:'Spain 🇪🇸',options:['Barcelona','Seville','Valencia','Madrid'],answer:'Madrid'},
    {tag:'GEO',prompt:'What country is the Eiffel Tower in?',word:'Eiffel Tower',options:['Italy','Belgium','France','Switzerland'],answer:'France'},
    {tag:'GEO',prompt:'Capital of China?',word:'China 🇨🇳',options:['Shanghai','Hong Kong','Guangzhou','Beijing'],answer:'Beijing'},
    {tag:'GEO',prompt:'Longest mountain range?',word:'Longest range',options:['Himalayas','Rockies','Alps','Andes'],answer:'Andes'},
    {tag:'GEO',prompt:'Colosseum is in which country?',word:'Colosseum',options:['Greece','Spain','Italy','Portugal'],answer:'Italy'},
    {tag:'GEO',prompt:'Capital of Mexico?',word:'Mexico 🇲🇽',options:['Guadalajara','Monterrey','Cancún','Mexico City'],answer:'Mexico City'},
    {tag:'GEO',prompt:'Capital of Argentina?',word:'Argentina 🇦🇷',options:['Córdoba','Rosario','Mendoza','Buenos Aires'],answer:'Buenos Aires'},
    {tag:'GEO',prompt:'Sphinx is in which country?',word:'Sphinx',options:['Sudan','Libya','Jordan','Egypt'],answer:'Egypt'},
    {tag:'GEO',prompt:'Capital of Russia?',word:'Russia 🇷🇺',options:['St. Petersburg','Novosibirsk','Kazan','Moscow'],answer:'Moscow'},
    {tag:'GEO',prompt:'What continent is Morocco in?',word:'Morocco',options:['Europe','Asia','South America','Africa'],answer:'Africa'},
    {tag:'GEO',prompt:'Largest lake in Africa?',word:'Largest African lake',options:['Lake Chad','Lake Tanganyika','Lake Malawi','Lake Victoria'],answer:'Lake Victoria'},
    {tag:'GEO',prompt:'Capital of South Korea?',word:'South Korea 🇰🇷',options:['Busan','Incheon','Gwangju','Seoul'],answer:'Seoul'},
    {tag:'GEO',prompt:'Currency of Japan?',word:'Japan currency',options:['Won','Yuan','Ringgit','Yen'],answer:'Yen'},
  ]},

  sports: { label:'Sports', icon:'⚽', color:'#FF3B3B', type:'mcq', questions:[
    {tag:'SPORTS',prompt:'Players on a football team?',word:'Football team',options:['9','10','11','12'],answer:'11'},
    {tag:'SPORTS',prompt:'Periods in basketball?',word:'NBA periods',options:['2','3','4','5'],answer:'4'},
    {tag:'SPORTS',prompt:'Country that invented football?',word:'Football origin',options:['Brazil','Spain','France','England'],answer:'England'},
    {tag:'SPORTS',prompt:'Length of a marathon?',word:'Marathon',options:['26.2 miles','24 miles','28 miles','30 miles'],answer:'26.2 miles'},
    {tag:'SPORTS',prompt:'Rings on the Olympic flag?',word:'Olympic rings',options:['4','5','6','7'],answer:'5'},
    {tag:'SPORTS',prompt:'Sport that uses a shuttlecock?',word:'Shuttlecock',options:['Tennis','Squash','Badminton','Polo'],answer:'Badminton'},
    {tag:'SPORTS',prompt:'Players in a basketball team?',word:'Basketball team',options:['4','5','6','7'],answer:'5'},
    {tag:'SPORTS',prompt:'Sport that uses a puck?',word:'Puck sport',options:['Lacrosse','Polo','Field hockey','Ice hockey'],answer:'Ice hockey'},
    {tag:'SPORTS',prompt:'Holes in standard golf?',word:'Golf holes',options:['9','12','16','18'],answer:'18'},
    {tag:'SPORTS',prompt:'Country with most World Cups?',word:'Most WC wins',options:['Germany','Argentina','Italy','Brazil'],answer:'Brazil'},
    {tag:'SPORTS',prompt:'Olympic pool length?',word:'Olympic pool',options:['25m','50m','75m','100m'],answer:'50m'},
    {tag:'SPORTS',prompt:'Sport played at Wimbledon?',word:'Wimbledon',options:['Golf','Cricket','Squash','Tennis'],answer:'Tennis'},
    {tag:'SPORTS',prompt:'Points for a touchdown?',word:'Touchdown',options:['4','5','6','7'],answer:'6'},
    {tag:'SPORTS',prompt:'What is a hat-trick?',word:'Hat-trick',options:['2 goals','3 goals','4 goals','5 goals'],answer:'3 goals'},
    {tag:'SPORTS',prompt:'Players in a baseball team?',word:'Baseball team',options:['7','8','9','10'],answer:'9'},
    {tag:'SPORTS',prompt:'Highest score in bowling?',word:'Bowling max',options:['250','275','300','325'],answer:'300'},
    {tag:'SPORTS',prompt:'Length of a soccer match?',word:'Soccer match',options:['80 min','85 min','90 min','95 min'],answer:'90 min'},
    {tag:'SPORTS',prompt:'Height of a basketball hoop?',word:'Hoop height',options:['8 ft','9 ft','10 ft','11 ft'],answer:'10 ft'},
    {tag:'SPORTS',prompt:'Players in a volleyball team?',word:'Volleyball',options:['5','6','7','8'],answer:'6'},
    {tag:'SPORTS',prompt:'LeBron James plays which sport?',word:'LeBron James',options:['Football','Baseball','Basketball','Hockey'],answer:'Basketball'},
    {tag:'SPORTS',prompt:'Players in a rugby union team?',word:'Rugby union',options:['13','14','15','16'],answer:'15'},
    {tag:'SPORTS',prompt:'Tour de France leader jersey color?',word:'TdF leader',options:['Green','Red','White','Yellow'],answer:'Yellow'},
    {tag:'SPORTS',prompt:'Sport played at the Masters?',word:'The Masters',options:['Tennis','Golf','Cricket','Swimming'],answer:'Golf'},
    {tag:'SPORTS',prompt:'Points for a 3-pointer?',word:'3-pointer',options:['2','3','4','5'],answer:'3'},
    {tag:'SPORTS',prompt:'National sport of Japan?',word:'Japan sport',options:['Judo','Karate','Sumo','Kendo'],answer:'Sumo'},
    {tag:'SPORTS',prompt:'Runs for a six in cricket?',word:'Cricket six',options:['4','5','6','7'],answer:'6'},
    {tag:'SPORTS',prompt:'Events in a decathlon?',word:'Decathlon',options:['8','9','10','12'],answer:'10'},
    {tag:'SPORTS',prompt:'Year of first modern Olympics?',word:'First Olympics',options:['1892','1896','1900','1904'],answer:'1896'},
    {tag:'SPORTS',prompt:'National sport of Canada?',word:'Canada sport',options:['Ice hockey','Curling','Lacrosse','Football'],answer:'Lacrosse'},
    {tag:'SPORTS',prompt:'Bull\'s eye in darts?',word:"Bull's eye",options:['25','50','75','100'],answer:'50'},
    {tag:'SPORTS',prompt:'Usain Bolt is known for?',word:'Usain Bolt',options:['Football','Swimming','Sprinting','Cycling'],answer:'Sprinting'},
    {tag:'SPORTS',prompt:'All Blacks are from which country?',word:'All Blacks',options:['Australia','South Africa','England','New Zealand'],answer:'New Zealand'},
    {tag:'SPORTS',prompt:'Sport that uses a foil?',word:'Foil weapon',options:['Archery','Fencing','Javelin','Polo'],answer:'Fencing'},
    {tag:'SPORTS',prompt:'Snooker red ball worth?',word:'Snooker red',options:['1','2','3','5'],answer:'1'},
    {tag:'SPORTS',prompt:'Sets to win in tennis grand slam (men)?',word:'Tennis sets',options:['2','3','4','5'],answer:'3'},
  ]},

  history: { label:'History', icon:'📜', color:'#c87cff', type:'mcq', questions:[
    {tag:'HISTORY',prompt:'First US president?',word:'1st US president',options:['Jefferson','Lincoln','Washington','Adams'],answer:'Washington'},
    {tag:'HISTORY',prompt:'When did WW2 end?',word:'WW2 ended',options:['1943','1944','1945','1946'],answer:'1945'},
    {tag:'HISTORY',prompt:'Year man first landed on the Moon?',word:'Moon landing',options:['1965','1967','1969','1971'],answer:'1969'},
    {tag:'HISTORY',prompt:'Who invented the telephone?',word:'Telephone',options:['Edison','Tesla','Bell','Marconi'],answer:'Bell'},
    {tag:'HISTORY',prompt:'Julius Caesar ruled which empire?',word:"Caesar's empire",options:['Greek','Ottoman','Roman','Persian'],answer:'Roman'},
    {tag:'HISTORY',prompt:'Berlin Wall fell in?',word:'Berlin Wall',options:['1987','1988','1989','1990'],answer:'1989'},
    {tag:'HISTORY',prompt:'First person in space?',word:'First in space',options:['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','John Glenn'],answer:'Yuri Gagarin'},
    {tag:'HISTORY',prompt:'Who painted the Mona Lisa?',word:'Mona Lisa',options:['Michelangelo','Raphael','Da Vinci','Botticelli'],answer:'Da Vinci'},
    {tag:'HISTORY',prompt:'Nigeria gained independence in?',word:'Nigeria independence',options:['1957','1958','1960','1963'],answer:'1960'},
    {tag:'HISTORY',prompt:'First female PM of UK?',word:'UK first female PM',options:['Theresa May','Angela Merkel','Margaret Thatcher','Indira Gandhi'],answer:'Margaret Thatcher'},
    {tag:'HISTORY',prompt:'War fought between 1914-1918?',word:'1914-1918',options:['WW2','Korean War','Vietnam War','WW1'],answer:'WW1'},
    {tag:'HISTORY',prompt:'Who wrote the Declaration of Independence?',word:'Declaration',options:['Washington','Franklin','Jefferson','Hamilton'],answer:'Jefferson'},
    {tag:'HISTORY',prompt:'Largest empire in history?',word:'Largest empire',options:['Roman','Ottoman','Mongol','British'],answer:'British'},
    {tag:'HISTORY',prompt:'Titanic sank in?',word:'Titanic sank',options:['1910','1912','1914','1916'],answer:'1912'},
    {tag:'HISTORY',prompt:'Who was Nelson Mandela?',word:'Nelson Mandela',options:['First president of Kenya','First black president of South Africa','First PM of Zimbabwe','First leader of Ghana'],answer:'First black president of South Africa'},
    {tag:'HISTORY',prompt:'Who invented the light bulb?',word:'Light bulb',options:['Tesla','Bell','Edison','Faraday'],answer:'Edison'},
    {tag:'HISTORY',prompt:'French Revolution began in?',word:'French Revolution',options:['1785','1787','1789','1791'],answer:'1789'},
    {tag:'HISTORY',prompt:'Cold War was between?',word:'Cold War',options:['US and UK','US and China','US and USSR','US and Germany'],answer:'US and USSR'},
    {tag:'HISTORY',prompt:'WW1 began in?',word:'WW1 started',options:['1912','1913','1914','1915'],answer:'1914'},
    {tag:'HISTORY',prompt:'First Emperor of China?',word:'First Chinese emperor',options:['Genghis Khan','Qin Shi Huang','Kublai Khan','Wu Zetian'],answer:'Qin Shi Huang'},
    {tag:'HISTORY',prompt:'American Civil War ended in?',word:'Civil War ended',options:['1863','1864','1865','1866'],answer:'1865'},
    {tag:'HISTORY',prompt:'Who discovered penicillin?',word:'Penicillin',options:['Pasteur','Darwin','Fleming','Curie'],answer:'Fleming'},
    {tag:'HISTORY',prompt:'First artificial satellite?',word:'First satellite',options:['Vostok','Explorer','Sputnik','Apollo'],answer:'Sputnik'},
    {tag:'HISTORY',prompt:'First woman to win Nobel Prize?',word:'First female Nobel',options:['Rosalind Franklin','Ada Lovelace','Marie Curie','Florence Nightingale'],answer:'Marie Curie'},
    {tag:'HISTORY',prompt:'Internet became public in?',word:'Public internet',options:['1989','1991','1993','1995'],answer:'1991'},
    {tag:'HISTORY',prompt:'Who built the Great Wall of China?',word:'Great Wall',options:['Ming Dynasty','Qin Dynasty','Han Dynasty','Tang Dynasty'],answer:'Qin Dynasty'},
    {tag:'HISTORY',prompt:'Famous Egyptian queen?',word:'Famous queen',options:['Nefertiti','Hatshepsut','Cleopatra','Berenice'],answer:'Cleopatra'},
    {tag:'HISTORY',prompt:'Ancient civilization that built pyramids?',word:'Pyramids built by',options:['Greeks','Romans','Mesopotamians','Egyptians'],answer:'Egyptians'},
    {tag:'HISTORY',prompt:'Ancient wonder in Alexandria?',word:'Alexandria wonder',options:['Colossus','Hanging Gardens','Lighthouse','Pyramids'],answer:'Lighthouse'},
  ]},

  music: { label:'Music', icon:'🎵', color:'#FF9C00', type:'mcq', questions:[
    {tag:'MUSIC',prompt:'Strings on a standard guitar?',word:'Guitar strings',options:['4','5','6','7'],answer:'6'},
    {tag:'MUSIC',prompt:'Fastest tempo marking?',word:'Fastest tempo',options:['Allegro','Presto','Vivace','Andante'],answer:'Presto'},
    {tag:'MUSIC',prompt:'Keys on a standard piano?',word:'Piano keys',options:['72','76','88','92'],answer:'88'},
    {tag:'MUSIC',prompt:'Bob Marley is known for?',word:'Bob Marley',options:['Calypso','Soca','Reggae','Ska'],answer:'Reggae'},
    {tag:'MUSIC',prompt:'Lowest male voice?',word:'Lowest male voice',options:['Tenor','Baritone','Alto','Bass'],answer:'Bass'},
    {tag:'MUSIC',prompt:'Notes in an octave?',word:'Octave notes',options:['6','7','8','9'],answer:'8'},
    {tag:'MUSIC',prompt:'K-pop originates from?',word:'K-pop origin',options:['Japan','China','South Korea','Taiwan'],answer:'South Korea'},
    {tag:'MUSIC',prompt:'BPM stands for?',word:'BPM',options:['Beats Per Measure','Beats Per Minute','Base Per Mix','Beat Pattern Mode'],answer:'Beats Per Minute'},
    {tag:'MUSIC',prompt:'Strings on a bass guitar?',word:'Bass guitar',options:['3','4','5','6'],answer:'4'},
    {tag:'MUSIC',prompt:'Highest female singing voice?',word:'Highest female voice',options:['Alto','Mezzo-soprano','Soprano','Contralto'],answer:'Soprano'},
    {tag:'MUSIC',prompt:'Michael Jackson defined which genre?',word:'Michael Jackson',options:['R&B','Pop','Soul','Funk'],answer:'Pop'},
    {tag:'MUSIC',prompt:'Largest orchestra section?',word:'Largest section',options:['Brass','Woodwind','Percussion','Strings'],answer:'Strings'},
    {tag:'MUSIC',prompt:'Note after G?',word:'After G',options:['A','B','H','G#'],answer:'A'},
    {tag:'MUSIC',prompt:'Afrobeats is?',word:'Afrobeats genre',options:['Caribbean music','West African pop','East African jazz','South African house'],answer:'West African pop'},
    {tag:'MUSIC',prompt:'Metronome is used for?',word:'Metronome',options:['Tuning instruments','Keeping tempo','Recording sound','Reading music'],answer:'Keeping tempo'},
    {tag:'MUSIC',prompt:'Forte means?',word:'Forte',options:['Slow','Soft','Loud','Fast'],answer:'Loud'},
    {tag:'MUSIC',prompt:'Piano (dynamic) means?',word:'Piano dynamic',options:['Slow','Loud','Soft','Fast'],answer:'Soft'},
    {tag:'MUSIC',prompt:'Semitones in an octave?',word:'Semitones',options:['10','11','12','13'],answer:'12'},
    {tag:'MUSIC',prompt:'A chord is?',word:'Chord',options:['Single note','Two notes','Three or more notes together','A scale'],answer:'Three or more notes together'},
    {tag:'MUSIC',prompt:'Time signature of a waltz?',word:'Waltz time',options:['2/4','3/4','4/4','6/8'],answer:'3/4'},
    {tag:'MUSIC',prompt:'Yo-Yo Ma plays which instrument?',word:'Yo-Yo Ma',options:['Violin','Viola','Cello','Double bass'],answer:'Cello'},
    {tag:'MUSIC',prompt:'A cappella means?',word:'A cappella',options:['Singing with instruments','Singing without instruments','A music genre','A choir type'],answer:'Singing without instruments'},
    {tag:'MUSIC',prompt:'Allegro means?',word:'Allegro',options:['Slow','Fast and lively','Very slow','Moderate'],answer:'Fast and lively'},
    {tag:'MUSIC',prompt:'What genre is Afrobeats often associated with Nigeria?',word:'Nigerian music',options:['Highlife','Fuji','Afrobeats','Juju'],answer:'Afrobeats'},
    {tag:'MUSIC',prompt:'How many lines in a musical staff?',word:'Musical staff',options:['3','4','5','6'],answer:'5'},
  ]},

  movies: { label:'Movies & TV', icon:'🎬', color:'#00E5FF', type:'mcq', questions:[
    {tag:'MOVIES',prompt:'Who played Iron Man in the MCU?',word:'Iron Man',options:['Chris Evans','Chris Hemsworth','Robert Downey Jr.','Mark Ruffalo'],answer:'Robert Downey Jr.'},
    {tag:'MOVIES',prompt:'Country that makes Nollywood films?',word:'Nollywood',options:['Ghana','Kenya','South Africa','Nigeria'],answer:'Nigeria'},
    {tag:'MOVIES',prompt:'CGI stands for?',word:'CGI',options:['Computer Game Interface','Computer Generated Imagery','Creative Graphic Integration','Color Grading Interface'],answer:'Computer Generated Imagery'},
    {tag:'MOVIES',prompt:'Show featuring the Iron Throne?',word:'Iron Throne',options:['Vikings','The Witcher','House of the Dragon','Game of Thrones'],answer:'Game of Thrones'},
    {tag:'MOVIES',prompt:'Who directed Inception?',word:'Inception',options:['James Cameron','Ridley Scott','Christopher Nolan','Quentin Tarantino'],answer:'Christopher Nolan'},
    {tag:'MOVIES',prompt:'Simba is what animal?',word:'Simba',options:['Cheetah','Leopard','Tiger','Lion'],answer:'Lion'},
    {tag:'MOVIES',prompt:'Language spoken in Squid Game?',word:'Squid Game',options:['Japanese','Mandarin','Korean','Thai'],answer:'Korean'},
    {tag:'MOVIES',prompt:'Who plays Black Panther?',word:'Black Panther',options:['Idris Elba','Will Smith','Michael B. Jordan','Chadwick Boseman'],answer:'Chadwick Boseman'},
    {tag:'MOVIES',prompt:'Netflix show set in Hawkins, Indiana?',word:'Hawkins, Indiana',options:['Dark','Outer Banks','The OA','Stranger Things'],answer:'Stranger Things'},
    {tag:'MOVIES',prompt:"Shrek's donkey friend is called?",word:"Shrek's friend",options:['Donkey','Puss','Ginger','Pinocchio'],answer:'Donkey'},
    {tag:'MOVIES',prompt:'Batman is set in which city?',word:'Batman city',options:['Metropolis','Star City','Gotham','Central City'],answer:'Gotham'},
    {tag:'MOVIES',prompt:'Who voiced Buzz Lightyear in Toy Story?',word:'Buzz Lightyear',options:['Tom Hanks','Tim Allen','Billy Crystal','John Goodman'],answer:'Tim Allen'},
    {tag:'MOVIES',prompt:'Who plays Thor in the MCU?',word:'Thor actor',options:['Chris Pratt','Chris Evans','Liam Hemsworth','Chris Hemsworth'],answer:'Chris Hemsworth'},
    {tag:'MOVIES',prompt:'Villain in The Lion King?',word:'Lion King villain',options:['Hyena','Zazu','Rafiki','Scar'],answer:'Scar'},
    {tag:'MOVIES',prompt:'Stranger Things is on which platform?',word:'Stranger Things platform',options:['Hulu','HBO Max','Disney+','Netflix'],answer:'Netflix'},
    {tag:'MOVIES',prompt:'Studio that made Spider-Verse?',word:'Spider-Verse',options:['Marvel Studios','Sony Pictures','Universal','Warner Bros'],answer:'Sony Pictures'},
    {tag:'MOVIES',prompt:'Who is the villain in Avengers: Infinity War?',word:'Infinity War villain',options:['Loki','Ultron','Thanos','Ronan'],answer:'Thanos'},
    {tag:'MOVIES',prompt:'What is the name of the main character in Breaking Bad?',word:'Breaking Bad',options:['Jesse Pinkman','Walter White','Hank Schrader','Mike Ehrmantraut'],answer:'Walter White'},
    {tag:'MOVIES',prompt:'What country produced Money Heist?',word:'Money Heist',options:['Italy','Brazil','Argentina','Spain'],answer:'Spain'},
    {tag:'MOVIES',prompt:"What is the name of Tony Stark's AI assistant?",word:"Tony's AI",options:['HAL','JARVIS','FRIDAY','VISION'],answer:'JARVIS'},
  ]},

  emojiMerge: { label:'Emoji Merge', icon:'🧩', color:'#FF3B3B', type:'type', questions:[
    {tag:'EMOJI MERGE',prompt:'What do these emojis represent together?',word:'🌊 + 🏄',answer:'SURFING'},
    {tag:'EMOJI MERGE',prompt:'What place do these show?',word:'🗼 + 🇫🇷',answer:'PARIS'},
    {tag:'EMOJI MERGE',prompt:'What concept is this?',word:'💰 + 🔗',answer:'BLOCKCHAIN'},
    {tag:'EMOJI MERGE',prompt:'What sport is this?',word:'⚽ + 👟',answer:'FOOTBALL'},
    {tag:'EMOJI MERGE',prompt:'What does this describe?',word:'🌧️ + 🌈',answer:'RAINBOW'},
    {tag:'EMOJI MERGE',prompt:'What concept is this?',word:'🎮 + 🏆',answer:'TOURNAMENT'},
    {tag:'EMOJI MERGE',prompt:'What do these represent?',word:'🐝 + 🏠',answer:'BEEHIVE'},
    {tag:'EMOJI MERGE',prompt:'What technology?',word:'🤖 + 🧠',answer:'AI'},
    {tag:'EMOJI MERGE',prompt:'What drink is this?',word:'🍋 + 💧',answer:'LEMONADE'},
    {tag:'EMOJI MERGE',prompt:'What concept is this?',word:'💡 + 🧠',answer:'IDEA'},
    {tag:'EMOJI MERGE',prompt:'What is this job?',word:'👨‍🍳 + 🍕',answer:'CHEF'},
    {tag:'EMOJI MERGE',prompt:'What does this mean?',word:'🤝 + 💼',answer:'DEAL'},
    {tag:'EMOJI MERGE',prompt:'What animal?',word:'🦁 + 👑',answer:'LION'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🖥️ + 👾',answer:'GAMING'},
    {tag:'EMOJI MERGE',prompt:'What holiday?',word:'🎃 + 👻',answer:'HALLOWEEN'},
    {tag:'EMOJI MERGE',prompt:'What is this concept?',word:'❤️ + 💔',answer:'HEARTBREAK'},
    {tag:'EMOJI MERGE',prompt:'What is this job?',word:'💉 + 🏥',answer:'DOCTOR'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'📚 + 🎓',answer:'GRADUATION'},
    {tag:'EMOJI MERGE',prompt:'What animal?',word:'🐴 + 🌈',answer:'UNICORN'},
    {tag:'EMOJI MERGE',prompt:'What place?',word:'🏖️ + 🌴',answer:'BEACH'},
    {tag:'EMOJI MERGE',prompt:'What vehicle?',word:'🚂 + 💨',answer:'TRAIN'},
    {tag:'EMOJI MERGE',prompt:'What season?',word:'☃️ + ❄️',answer:'WINTER'},
    {tag:'EMOJI MERGE',prompt:'What crypto concept?',word:'⛏️ + 💰',answer:'MINING'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🎤 + 🎶',answer:'SINGING'},
    {tag:'EMOJI MERGE',prompt:'What event?',word:'🎉 + 🎂',answer:'BIRTHDAY'},
    {tag:'EMOJI MERGE',prompt:'What sport?',word:'🥊 + 🥋',answer:'BOXING'},
    {tag:'EMOJI MERGE',prompt:'What movie genre?',word:'👻 + 😱',answer:'HORROR'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🔐 + 🔑',answer:'PASSWORD'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'📱 + 💸',answer:'PAYMENT'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🌱 + 💧',answer:'GROWTH'},
    {tag:'EMOJI MERGE',prompt:'What animal?',word:'🐘 + 🌍',answer:'ELEPHANT'},
    {tag:'EMOJI MERGE',prompt:'What activity?',word:'🎵 + 👂',answer:'LISTENING'},
    {tag:'EMOJI MERGE',prompt:'What sport?',word:'🏇 + 🐎',answer:'HORSERACING'},
    {tag:'EMOJI MERGE',prompt:'What concept?',word:'🌍 + 🔥',answer:'GLOBALWARMING'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🍎 + 📱',answer:'APPLE'},
    {tag:'EMOJI MERGE',prompt:'What game mode?',word:'⏱️ + 🎮',answer:'TIMEATTACK'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🦸 + 🦹',answer:'BATTLE'},
    {tag:'EMOJI MERGE',prompt:'What event?',word:'🏃 + 🏁',answer:'RACE'},
    {tag:'EMOJI MERGE',prompt:'What is this?',word:'🌙 + ⭐',answer:'NIGHT'},
    {tag:'EMOJI MERGE',prompt:'What concept?',word:'🔥 + 💧',answer:'STEAM'},
  ]},

  unscramble: { label:'Word Unscramble', icon:'⌨️', color:'#00E5FF', type:'type', questions:[
    {tag:'UNSCRAMBLE',prompt:'Unscramble this crypto word:',word:'OLIARI',answer:'RIALO'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'KBCHINOLA',answer:'BLOCKCHAIN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TNOKE',answer:'TOKEN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TGNSAKI',answer:'STAKING'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'LATELW',answer:'WALLET'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TNFM',answer:'MINT'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'EGIMNR',answer:'MINER'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'PCYORT',answer:'CRYPTO'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'NETEHRMU',answer:'ETHEREUM'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'NBOCEKI',answer:'BITCOIN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'ADGTRNI',answer:'TRADING'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'GIMNNI',answer:'MINING'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TCELBOKHIN',answer:'BLOCKCHAIN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TOEKN',answer:'TOKEN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'SNCUIRTECY',answer:'CURRENCY'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'DTEALWE',answer:'WALETED'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'RALBGLE',answer:'GARBELL'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'ODECC',answer:'CODEC'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'GDRAITN',answer:'TRADING'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TGEDRNIA',answer:'NITROGEN'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'RNCKETOW',answer:'NETWORK'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'CRTNOCAT',answer:'CONTRACT'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'IORPLTFAM',answer:'PLATFORM'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'CHETAINX',answer:'EXCHANGE'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'DESLRCNO',answer:'CONSLDER'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'LCERTIPAO',answer:'REPLICATO'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'ISOTNVARNE',answer:'INNOVATION'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TCIOSPRNE',answer:'INSPECTOR'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'DAELINRC',answer:'CALENDAR'},
    {tag:'UNSCRAMBLE',prompt:'Unscramble this word:',word:'TRMKAE',answer:'MARKET'},
  ]},
};

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function getDailySeed() {
  const d = new Date();
  return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
}

function seededShuffle(arr, seed) {
  const a = [...arr];
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  for (let i = a.length - 1; i > 0; i--) {
    h = (Math.imul(h ^ (h >>> 16), 0x45d9f3b)) | 0;
    const j = Math.abs(h) % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function getQuestionsForMode({ mode = 'reflex', categories = [], count = 10, daily = false } = {}) {
  let pool = [];
  if (mode === 'timeattack') {
    ['math','rialo','science','geography','sports','history','music','movies'].forEach(cat => {
      pool.push(...CATEGORIES[cat].questions);
    });
  } else if (mode === 'emoji') {
    pool = CATEGORIES.emojiMerge.questions;
  } else if (mode === 'unscramble') {
    pool = CATEGORIES.unscramble.questions;
  } else if (categories.length > 0) {
    categories.forEach(cat => {
      if (CATEGORIES[cat]) pool.push(...CATEGORIES[cat].questions);
    });
  } else {
    ['math','rialo','science','geography','sports'].forEach(cat => {
      pool.push(...CATEGORIES[cat].questions);
    });
  }
  if (daily) {
    const seed = getDailySeed();
    return seededShuffle(pool, seed).slice(0, count);
  }
  return shuffle(pool).slice(0, count);
}

function getCategoryList() {
  return Object.entries(CATEGORIES).map(([key, val]) => ({
    key, label: val.label, icon: val.icon, color: val.color, type: val.type, count: val.questions.length,
  }));
}

function getTotalQuestions() {
  return Object.values(CATEGORIES).reduce((sum, cat) => sum + cat.questions.length, 0);
}

module.exports = { CATEGORIES, getQuestionsForMode, getCategoryList, getTotalQuestions, getDailySeed };
